import javax.swing.*;// imports Swing GUI components
import java.awt.*;// imports AWT classes like Font, Color
import java.awt.event.ActionEvent;// event object for button actions
import java.awt.event.ActionListener;// interface used to handle button click events

// This class creates the GUI and handles button click events
public class CreateButton implements ActionListener{

    JButton button = new JButton();// button component that the user will click
    JLabel label = new JLabel();// label that will display an image after button click

    public static void main(String[] args){
        new CreateButton(); // creates an object which calls the constructor to build the GUI
    }

    public CreateButton(){

        ImageIcon icon = new ImageIcon("75px.png");// image for the label
        ImageIcon image = new ImageIcon("50px.png");// image that will appear on the button

        label.setIcon(icon); // sets the icon for the label
        label.setBounds(150,250,150,150);// sets position and size of the label
        label.setVisible(false);// label is hidden initially

        button.setBounds(130,100,200,100);// sets position and size of the button
        button.setText("Button");// text displayed on the button
        button.setFocusable(false);// removes the focus border when clicked
        button.setIcon(image);// sets icon image on the button

        button.setHorizontalTextPosition(JButton.CENTER); // aligns button text horizontally relative to the icon
        button.setVerticalTextPosition(JButton.BOTTOM);   // places text below the icon

        button.setFont(new Font("Comic Sans",Font.ITALIC,25)); // sets font style and size of the button text

        button.setIconTextGap(-6);// controls spacing between icon and text

        button.setForeground(Color.BLUE);// sets color of the button text
        button.setBackground(Color.lightGray);// sets background color of the button

        button.setBorder(BorderFactory.createEtchedBorder()); // creates an etched border style for the button

        //button.setEnabled(false);// if enabled, this would disable the button (unclickable)

        JFrame frame = new JFrame();// creates the main application window
        frame.setVisible(true);// makes the frame visible on screen
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // closes program when window is closed
        frame.setSize(500,500);// sets window size
        frame.setLayout(null);// disables layout manager to allow manual positioning

        frame.add(label);// adds the label to the frame

        button.addActionListener(this);// registers this class as the event listener for the button
        // when button is clicked, actionPerformed() will run

        frame.add(button); // adds the button to the frame
    }

    @Override
    public void actionPerformed(ActionEvent e) {// method that runs when an action event occurs
        if(e.getSource()==button){// checks if the event was generated by this button
            label.setVisible(true);// makes the hidden label visible after the button is clicked
        }
    }
}